# LEON 3 Makefile
# Compiles ArchC simulator

TARGET=leon3
INC_DIR := -I. -I$(ARCHC_PATH)/install/include/archc -I$(SYSTEMC)/install/include -I$(TLM_PATH) 

SRCS := ac_tlm_signal_port.cpp leon3_trap_selector.cpp leon3_arch.cpp leon3_arch_ref.cpp  leon3.cpp  leon3_isa.cpp leon3_isa_init.cpp leon3_intr_handlers.cpp

OBJS := $(SRCS:.cpp=.o)

#------------------------------------------------------
.SILENT:
#------------------------------------------------------
.SUFFIXES: .cc .cpp .o
#-----------------------------------------------------
lib: all
	ar r lib$(TARGET).a $(OBJS)
#------------------------------------------------------
all: leon3.cpp $(OBJS)
#------------------------------------------------------
clean:
	rm -f $(OBJS) *~ *.o *.a
#------------------------------------------------------
distclean: clean
	if test -f Makefile.archc; then $(MAKE) -f Makefile.archc distclean; fi;
#------------------------------------------------------
.cpp.o:
	$(CC) $(CFLAGS) $(INC_DIR) -c -g $<
#------------------------------------------------------
.cc.o:
	$(CC) $(CFLAGS) $(INC_DIR) -c -g $<
#------------------------------------------------------
leon3.cpp:
	echo --- No simulator found, using acsim to generate one.
	$(ARCHC_PATH)/install/bin/acsim leon3.ac -ndc
	$(MAKE) all
