# ####################################################
# GPTIMER Test
# ####################################################

CC = sparc-elf-gcc
CFLAGS = -msoft-float -specs=archc -g
LDFLAGS = -lm

TARGET = 
INC_DIR := -I.

SRCS := 000.gptimer.test.c 001.gptimer.test.c 002.gptimer.test.c 003.gptimer.test.c bogo.mips.test.c
OBJS := $(SRCS:.c=.o)

#------------------------------------------------------
.SILENT:

#------------------------------------------------------
.SUFFIXES: .o .c .h

#------------------------------------------------------
all: $(OBJS)
	$(CC) 000.gptimer.test.o $(CFLAGS) -o 000.gptimer.test.x $(LDFLAGS)
	$(CC) 001.gptimer.test.o $(CFLAGS) -o 001.gptimer.test.x $(LDFLAGS)
	$(CC) 002.gptimer.test.o $(CFLAGS) -o 002.gptimer.test.x $(LDFLAGS)
	$(CC) 003.gptimer.test.o $(CFLAGS) -o 003.gptimer.test.x $(LDFLAGS)
	$(CC) bogo.mips.test.o $(CFLAGS) -o bogo.mips.test.x $(LDFLAGS)
#------------------------------------------------------
clean:
	rm -f *.o *~ *x
#------------------------------------------------------
distclean: clean
#------------------------------------------------------
bin:
	tar xzf serialtest-bin.tgz
#------------------------------------------------------
.c.o:
	$(CC) -c $(CFLAGS) $(INC_DIR) -c $<
	



